In [3]:
# First channel is calculated as expected only using the weights associated with the first channel
# also kernel is moving as expected horizontally
# padding is done only to the left and right edges and 1 more extra padding to the right edge as the kernel length is even

from tensorflow.keras.layers import Conv2D
from tensorflow.keras import regularizers
import numpy as np

conv2d_strides = 1
kernel_regularizer = 1e-5

reshaped_input = np.ones(5*24).reshape(1,5,24,1)
print(reshaped_input[0,:,:,0])
reshaped_input2 = reshaped_input.copy()
reshaped_input2[:,1,:,:]  = 2*reshaped_input2[:,1,:,:]
reshaped_input2[:,2,:,:]  = 3*reshaped_input2[:,2,:,:]

conv2d_layer1 = Conv2D(2, (1,4), strides = conv2d_strides,
                           kernel_regularizer=regularizers.l2(kernel_regularizer),
                           padding='same', use_bias=True,
                           kernel_initializer='glorot_uniform',
                           input_shape=(5,24))

output = conv2d_layer1(reshaped_input)
output2 = conv2d_layer1(reshaped_input2)

weights = conv2d_layer1.get_weights()

first_channel_weights = weights[0][0,:,:,0]
print(first_channel_weights)
print(first_channel_weights[0][0]+first_channel_weights[1][0]+first_channel_weights[2][0]+first_channel_weights[3][0])
print(first_channel_weights[1][0]+first_channel_weights[2][0]+first_channel_weights[3][0])
print(first_channel_weights[0][0]+first_channel_weights[1][0]+first_channel_weights[2][0])
print(first_channel_weights[0][0]+first_channel_weights[1][0])
print(output[0,:,:,0])
print(output2[0,:,:,0])



[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]
[[ 0.56266063]
 [-0.00705808]
 [-0.00824428]
 [-0.05289209]]
0.4944662
-0.06819445
0.5473583
0.55560255
tf.Tensor(
[[-0.06819445  0.4944662   0.4944662   0.4944662   0.4944662   0.4944662
   0.4944662   0.4944662   0.4944662   0.4944662   0.4944662   0.4944662
   0.4944662   0.4944662   0.4944662   0.4944662   0.4944662   0.4944662
   0.4944662   0.4944662   0.4944662   0.4944662   0.5473583   0.55560255]
 [-0.06819445  0.4944662   0.4944662   0.4944662   0.4944662   0.4944662
   0.4944662   0.4944662   0.4944662   0.4944662   0.4944662   0.4944662
   0.4944662   0.4944662   0.4944662   0.4944662   0.4944662   0.4944